"""Technicial Questions

Revision ID: 3e8a1ba55e27
Revises: f4b8104a422a
Create Date: 2023-03-05 12:48:55.442029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8a1ba55e27'
down_revision = 'f4b8104a422a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicial_question', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('Easy', 'Moderate', 'Difficult', name='difficulty'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicial_question', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('Easy', 'Moderate', 'Difficult', name='difficulty'),
               type_=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
