"""initial migration

Revision ID: 726090af59d0
Revises: 
Create Date: 2023-02-10 22:55:46.611341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726090af59d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.BLOB(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('profile_pic',
               existing_type=sa.BLOB(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('company_logo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('company_logo',
               existing_type=sa.String(length=200),
               type_=sa.BLOB(),
               existing_nullable=False)

    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=200),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('resume',
               existing_type=sa.String(length=200),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
