"""Relationship

Revision ID: 74fa4ac61b57
Revises: dfad2f158923
Create Date: 2023-03-10 11:55:03.246516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fa4ac61b57'
down_revision = 'dfad2f158923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.String(length=500), nullable=False),
    sa.Column('owner_company', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Enum('Easy', 'Moderate', 'Difficult', name='difficulty'), nullable=True),
    sa.Column('option1', sa.String(length=2000), nullable=False),
    sa.Column('option2', sa.String(length=2000), nullable=False),
    sa.Column('option3', sa.String(length=2000), nullable=False),
    sa.Column('correctoption', sa.String(length=2000), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_company'], ['company.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_company', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('job_role', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_company'], ['company.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_test',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['technical_question.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['technical_test.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'test_id')
    )
    op.drop_table('technicial_question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicial_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=9), nullable=True),
    sa.Column('option1', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('option2', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('option3', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('correctoption', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('company_username', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_test')
    op.drop_table('technical_test')
    op.drop_table('technical_question')
    # ### end Alembic commands ###
