"""Technicial Questions

Revision ID: e3b158a2ceab
Revises: 54523e72916d
Create Date: 2023-03-06 19:09:10.530887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b158a2ceab'
down_revision = '54523e72916d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicial_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicial_question', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
