"""Technicial Questions

Revision ID: f4b8104a422a
Revises: 726090af59d0
Create Date: 2023-03-05 11:57:44.055127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b8104a422a'
down_revision = '726090af59d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicial_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Enum('Easy', 'Medium', 'Hard'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcq_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=2000), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['technicial_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcq_option')
    op.drop_table('technicial_question')
    # ### end Alembic commands ###
